######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 17 15:17:57 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /ad/eng/users/a/a/aaparici/lab5/qt/. .

# Input
SOURCES += main.cpp
