# Author: Alejandro Aparicio email: aaparici@bu.edu 
# EC535 Spring 2017


counterinfo: counterinfo.o 
	/ad/eng/courses/ec/ec535/gumstix/oe/cross/bin/arm-linux-gcc -Os -o counterinfo counterinfo.c

clean: 
	rm counterinfo counterinfo.o
